---
- name: 'IAC Ansible Discovery'
  hosts: 'all'
  tasks:
    - name: 'Install PHP5'
      ansible.builtin.apt:
        name: php5
        state: latest
      become: true
    - name: 'Install Apache2'
      ansible.builtin.apt:
        name: apache2
        state: latest
      become: true
    - name: 'Install ModPHP'
      ansible.builtin.apt:
        name: libapache2-mod-php5
        state: latest
      become: true
